language: go
dist: bionic

go:
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

services:
  - docker

script: make test

before_install:
  - sudo apt-get install -y curl wget software-properties-common apt-transport-https ca-certificates gnupg2
  - sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
  - sudo wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
  - sudo apt-get update
  - sudo apt-get install -y librdkafka1 librdkafka-dev
